# Generated by Django 4.0.2 on 2022-04-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vinculo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Radicado', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Grado_o_Área', models.CharField(max_length=50)),
                ('Peticion', models.BooleanField()),
                ('Queja', models.BooleanField()),
                ('Sugerencia', models.BooleanField()),
                ('Reconocimiento', models.BooleanField()),
                ('Dependencia', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=50)),
                ('Deescripcion', models.TextField()),
                ('Vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vinculo')),
            ],
        ),
    ]
