# Generated by Django 4.0.4 on 2022-04-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PQRS',
            new_name='registro',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Grado_o_Área',
            new_name='Grado_o_area',
        ),
    ]
