# Generated by Django 4.0.4 on 2022-04-20 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_vinculo_vinculo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrosNuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Radicado', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Grado_o_area', models.CharField(max_length=50)),
                ('vinculo', models.IntegerField(choices=[[0, 'directivos'], [1, 'docentes'], [2, 'abministrativos'], [3, 'padre de familia'], [4, 'estudiante'], [5, 'otros']])),
                ('Peticion', models.BooleanField()),
                ('Queja', models.BooleanField()),
                ('Sugerencia', models.BooleanField()),
                ('Reconocimiento', models.BooleanField()),
                ('Dependencia', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=50)),
                ('Deescripcion', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vinculo')),
            ],
        ),
        migrations.DeleteModel(
            name='registro',
        ),
    ]
