# Generated by Django 4.0.4 on 2022-04-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_registrosnuevo_delete_registrosnuevos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosnuevo',
            name='tipo',
            field=models.IntegerField(choices=[[2, 'peticion'], [3, 'queja'], [4, 'sugerencia'], [5, 'reconocimiento']]),
        ),
    ]
