# Generated by Django 4.0.2 on 2022-04-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_registrosnuevo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosnuevo',
            name='vinculo',
            field=models.IntegerField(choices=[[0, 'directivos'], [1, 'docentes'], [2, 'administrativos'], [3, 'padre de familia'], [4, 'estudiante'], [5, 'otros']]),
        ),
    ]
