# Generated by Django 4.0.2 on 2022-04-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_registro_delete_registrosnuevo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vinculo',
            new_name='Vinculos',
        ),
    ]
