# Generated by Django 4.0.2 on 2022-04-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_vinculo_vinculos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vinculos',
            new_name='Vinculo',
        ),
    ]
