# Generated by Django 4.0.2 on 2022-04-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_vinculos_vinculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='norma',
            new_name='Terminos_y_condiciones',
        ),
    ]
